version: "3.8"
services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: incidentpulse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/incidentpulse
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # add mail / other ENV vars here
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db-data: