-- Baseline schema for IncidentPulse.
-- Column names/types intentionally mirror what Hibernate generates from the
-- @Entity classes so that `spring.jpa.hibernate.ddl-auto=validate` passes in
-- dev/prod. Hibernate owns nothing at runtime anymore; Flyway owns the schema.

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL UNIQUE,
    username        VARCHAR(255) NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    created_at      TIMESTAMP(6),
    active          BOOLEAN      NOT NULL DEFAULT FALSE,
    role            VARCHAR(255) NOT NULL,
    team            VARCHAR(255) NOT NULL
);

CREATE TABLE incident (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               VARCHAR(255),
    created_by_user_id  BIGINT REFERENCES users (id),
    assigned_to_user_id BIGINT REFERENCES users (id),
    status              VARCHAR(255),
    severity            VARCHAR(255),
    message             VARCHAR(255),
    created_at          TIMESTAMP(6),
    updated_at          TIMESTAMP(6)
);

CREATE TABLE on_call_shift (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT REFERENCES users (id),
    started_at    TIMESTAMP(6),
    end_at        TIMESTAMP(6),
    created_at    TIMESTAMP(6)
);

CREATE TABLE incident_history (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id   BIGINT REFERENCES incident (id),
    actor_user_id BIGINT REFERENCES users (id),
    message       VARCHAR(255),
    action_type   VARCHAR(255),
    from_status   VARCHAR(255),
    to_status     VARCHAR(255),
    created_at    TIMESTAMP(6)
);

CREATE INDEX idx_incident_status ON incident (status);
CREATE INDEX idx_incident_severity ON incident (severity);
CREATE INDEX idx_incident_assigned_to ON incident (assigned_to_user_id);
CREATE INDEX idx_incident_history_incident ON incident_history (incident_id);
